name: GuiceHibernatePlugin
version: '${version}'
main: borg.locutus.guicehibernateplugin.GuiceHibernatePlugin

commands:
  playerstats:
    description: Gets the kill/death stats of a uuid
    usage: /playerstats <uuid>