name: GuiceHibernatePlugin
version: '${version}'
main: borg.locutus.guicehibernateplugin.GuiceHibernatePlugin

commands:
  createstudent:
    description: Creates a student entity in the database
    usage: /createstudent <Name> <Age>